name: PHP Composer

on:
  push:
    branches: [ leancloud ]
  pull_request:
    branches: [ leancloud ]
    
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
      env:
        COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Install dependencies
      run: composer install --prefer-dist
